<?php

namespace Tests\Feature;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Http;
use Tests\TestCase;

class ApiBackendTest extends TestCase
{
    use RefreshDatabase;

    public function test_health_endpoint_returns_ok(): void
    {
        $response = $this->getJson('/api/health');

        $response
            ->assertOk()
            ->assertJson([
                'status' => 'ok',
                'provider' => 'openai',
            ]);
    }

    public function test_chat_send_returns_assistant_message_and_persists_messages(): void
    {
        config([
            'mullem.ai.api_key' => 'test-key',
            'mullem.ai.endpoint' => 'https://api.openai.com/v1/responses',
            'mullem.ai.model' => 'gpt-5.4-mini',
        ]);

        Http::fake([
            'https://api.openai.com/v1/responses' => Http::response([
                'output_text' => 'الحضارة الرومانية حضارة قديمة نشأت في روما وأثرت في القانون والسياسة والعمران.',
            ], 200),
        ]);

        $response = $this->postJson('/api/chat/send', [
            'guest_session_id' => 'test-guest-1',
            'message' => 'ماهي الحضارة الرومانية؟',
            'subject' => 'التاريخ',
        ]);

        $response
            ->assertOk()
            ->assertJsonPath('success', true)
            ->assertJsonPath('data.assistant_message.source', 'openai')
            ->assertJsonPath(
                'data.assistant_message.body',
                'الحضارة الرومانية حضارة قديمة نشأت في روما وأثرت في القانون والسياسة والعمران.'
            );

        $this->assertDatabaseHas('conversations', [
            'guest_session_id' => 'test-guest-1',
            'subject' => 'التاريخ',
        ]);

        $this->assertDatabaseCount('messages', 2);
    }

    public function test_solve_question_returns_normalized_payload(): void
    {
        config([
            'mullem.ai.api_key' => 'test-key',
            'mullem.ai.endpoint' => 'https://api.openai.com/v1/responses',
            'mullem.ai.model' => 'gpt-5.4-mini',
        ]);

        Http::fake([
            'https://api.openai.com/v1/responses' => Http::response([
                'output_text' => json_encode([
                    'question_type' => 'definition',
                    'answer' => 'الحضارة الرومانية حضارة قامت في روما القديمة وتميزت بالقانون والهندسة والتنظيم الإداري.',
                    'explanation' => 'كانت من أبرز حضارات العالم القديم وامتد تأثيرها إلى أوروبا ومناطق واسعة.',
                    'display_text' => 'الحضارة الرومانية حضارة قامت في روما القديمة وتميزت بالقانون والهندسة والتنظيم الإداري.',
                    'confidence' => 0.93,
                    'matched_source' => 'openai_api',
                    'source_trace' => [
                        [
                            'source' => 'openai_api',
                            'detail' => 'Generated by test fake',
                            'score' => 0.93,
                            'metadata' => new \stdClass(),
                        ],
                    ],
                ], JSON_UNESCAPED_UNICODE),
            ], 200),
        ]);

        $response = $this->postJson('/api/solve-question', [
            'question' => 'ماهي الحضارة الرومانية؟',
        ]);

        $response
            ->assertOk()
            ->assertJsonPath('matched_source', 'openai_api')
            ->assertJsonPath('hidden_analysis.question_type', 'definition')
            ->assertJsonPath(
                'answer',
                'الحضارة الرومانية حضارة قامت في روما القديمة وتميزت بالقانون والهندسة والتنظيم الإداري.'
            );
    }

    public function test_auth_register_login_and_me_flow(): void
    {
        $register = $this->postJson('/api/auth/register', [
            'name' => 'طالب API',
            'email' => 'api-student@example.com',
            'password' => 'Student@2026',
            'password_confirmation' => 'Student@2026',
            'grade' => 'الثاني الثانوي',
            'stage' => 'ثانوي',
            'device_name' => 'phpunit',
        ]);

        $register
            ->assertCreated()
            ->assertJsonPath('success', true)
            ->assertJsonPath('data.user.email', 'api-student@example.com');

        $token = $register->json('data.token');

        $this->assertNotEmpty($token);
        $this->assertDatabaseHas('api_tokens', [
            'user_id' => User::query()->where('email', 'api-student@example.com')->value('id'),
        ]);

        $me = $this->withHeader('Authorization', "Bearer {$token}")
            ->getJson('/api/auth/me');

        $me
            ->assertOk()
            ->assertJsonPath('data.user.email', 'api-student@example.com')
            ->assertJsonPath('data.user.role', 'student');

        $login = $this->postJson('/api/auth/login', [
            'email' => 'api-student@example.com',
            'password' => 'Student@2026',
            'device_name' => 'phpunit-login',
        ]);

        $login
            ->assertOk()
            ->assertJsonPath('success', true)
            ->assertJsonPath('data.user.email', 'api-student@example.com');
    }

    public function test_admin_stats_and_users_require_valid_admin_token(): void
    {
        $admin = User::factory()->create([
            'name' => 'Admin Tester',
            'email' => 'admin-tester@example.com',
            'password' => 'Mullem@2026',
            'role' => 'admin',
            'status' => 'active',
        ]);

        $student = User::factory()->create([
            'name' => 'Student Tester',
            'email' => 'student-tester@example.com',
            'password' => 'Student@2026',
            'role' => 'student',
            'status' => 'active',
        ]);

        $login = $this->postJson('/api/auth/login', [
            'email' => $admin->email,
            'password' => 'Mullem@2026',
            'device_name' => 'phpunit-admin',
        ]);

        $token = $login->json('data.token');

        $stats = $this->withHeader('Authorization', "Bearer {$token}")
            ->getJson('/api/admin/stats');

        $stats
            ->assertOk()
            ->assertJsonPath('data.stats.admins_count', 1)
            ->assertJsonPath('data.stats.students_count', 1);

        $users = $this->withHeader('Authorization', "Bearer {$token}")
            ->getJson('/api/admin/users');

        $users
            ->assertOk()
            ->assertJsonPath('data.pagination.total', 2)
            ->assertJsonFragment(['email' => $student->email]);
    }
}
